; Listing generated by Microsoft (R) Optimizing Compiler Version 19.12.25831.0 

	TITLE	C:\Users\Stuart\Desktop\Projects4\ColorBlend\ColorBlender\Utilities.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?BitCounts@@3PAEA				; BitCounts
_DATA	SEGMENT
?BitCounts@@3PAEA DB 00H				; BitCounts
	DB	01H
	DB	01H
	DB	02H
	DB	01H
	DB	02H
	DB	02H
	DB	03H
	DB	01H
	DB	02H
	DB	02H
	DB	03H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	01H
	DB	02H
	DB	02H
	DB	03H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	01H
	DB	02H
	DB	02H
	DB	03H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	01H
	DB	02H
	DB	02H
	DB	03H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	05H
	DB	06H
	DB	06H
	DB	07H
	DB	01H
	DB	02H
	DB	02H
	DB	03H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	05H
	DB	06H
	DB	06H
	DB	07H
	DB	02H
	DB	03H
	DB	03H
	DB	04H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	05H
	DB	06H
	DB	06H
	DB	07H
	DB	03H
	DB	04H
	DB	04H
	DB	05H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	05H
	DB	06H
	DB	06H
	DB	07H
	DB	04H
	DB	05H
	DB	05H
	DB	06H
	DB	05H
	DB	06H
	DB	06H
	DB	07H
	DB	05H
	DB	06H
	DB	06H
	DB	07H
	DB	06H
	DB	07H
	DB	07H
	DB	08H
	ORG $+16
_DATA	ENDS
PUBLIC	?BitCountTable2@@YGHE@Z				; BitCountTable2
PUBLIC	_BitCount@4
PUBLIC	_BitCountTable@4
; Function compile flags: /Odtp
; File c:\users\stuart\desktop\projects4\colorblend\colorblender\utilities.cpp
_TEXT	SEGMENT
_SourceValue$ = 8					; size = 1
_BitCountTable@4 PROC

; 285  : {

	push	ebp
	mov	ebp, esp

; 286  :     return BitCounts[SourceValue];

	movzx	eax, BYTE PTR _SourceValue$[ebp]
	movzx	eax, BYTE PTR ?BitCounts@@3PAEA[eax]

; 287  : }

	pop	ebp
	ret	4
_BitCountTable@4 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\stuart\desktop\projects4\colorblend\colorblender\utilities.cpp
_TEXT	SEGMENT
_Count$ = -4						; size = 4
_SourceValue$ = 8					; size = 1
_BitCount@4 PROC

; 295  : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 296  :     int Count = 0;

	mov	DWORD PTR _Count$[ebp], 0

; 297  :     for (Count = 0; SourceValue; Count++)

	mov	DWORD PTR _Count$[ebp], 0
	jmp	SHORT $LN4@BitCount
$LN2@BitCount:
	mov	eax, DWORD PTR _Count$[ebp]
	add	eax, 1
	mov	DWORD PTR _Count$[ebp], eax
$LN4@BitCount:
	movzx	ecx, BYTE PTR _SourceValue$[ebp]
	test	ecx, ecx
	je	SHORT $LN3@BitCount

; 298  :     {
; 299  :         SourceValue &= SourceValue - 1;

	movzx	edx, BYTE PTR _SourceValue$[ebp]
	sub	edx, 1
	movzx	eax, BYTE PTR _SourceValue$[ebp]
	and	eax, edx
	mov	BYTE PTR _SourceValue$[ebp], al

; 300  :     }

	jmp	SHORT $LN2@BitCount
$LN3@BitCount:

; 301  :     return Count;

	mov	eax, DWORD PTR _Count$[ebp]

; 302  : }

	mov	esp, ebp
	pop	ebp
	ret	4
_BitCount@4 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\stuart\desktop\projects4\colorblend\colorblender\utilities.cpp
_TEXT	SEGMENT
_SourceValue$ = 8					; size = 1
?BitCountTable2@@YGHE@Z PROC				; BitCountTable2

; 290  : {

	push	ebp
	mov	ebp, esp

; 291  :     return BitCountTable(SourceValue);

	movzx	eax, BYTE PTR _SourceValue$[ebp]
	push	eax
	call	_BitCountTable@4

; 292  : }

	pop	ebp
	ret	4
?BitCountTable2@@YGHE@Z ENDP				; BitCountTable2
_TEXT	ENDS
END
